spring:
  datasource:
    dynamic:
      primary: primary
      dynamic:
        primary:
          driver-class-name: oracle.jdbc.OracleDriver
          jdbc-url: jdbc:oracle:thin:@//10.170.6.140:1521/imTest
          username: IMWEB
          password: NzmNXWDwxm2
          hikari:
            maximum-pool-size: 10
        secondary:
          driverClassName: oracle.jdbc.OracleDriver
          jdbc-url: jdbc:oracle:thin:@//10.170.6.144:1521/qtechIm
          username: imBiz
          password: M5F5JkfnQ
          hikari:
            maximum-pool-size: 10
